---
label: Project
hide_body: false
fields:
- name: blocks
  type: blocks
  label: Blocks
  template_types:
  - project
  - author
  - journal
  config:
    min: 
    max: 
  description: blocks here
pages:
- projects/3d-graff.md
- projects/chelsea-landmark.md
- projects/ios-concept.md
- projects/sunk.md
